apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rc-large-pvc
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi