apiVersion: v1
kind: Pod
metadata:
  name: rc-large-pvc-pod # YOUR POD NAME HERE
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central 
  containers:
    - name: rc-large-pvc-pod # YOUR CONTAINER NAME HERE
      # image: ubuntu:20.04
      image: rchristopher27/rc-research-image:mmpretrain2
      command: ["sh", "-c", "echo 'RChristopher Large PVC Pod' && sleep infinity"]
      resources:
        limits:
          memory: 10Gi
          cpu: 2
          # nvidia.com/gpu: '1'
        requests:
          memory: 10Gi
          cpu: 2
          # nvidia.com/gpu: '1'
      volumeMounts:
        - mountPath: /rchristopher/data
          name: rc-large-pvc # YOUR PVC NAME HERE
  volumes:
  - name: rc-large-pvc # YOUR PVC NAME HERE
    persistentVolumeClaim:
      claimName: rc-large-pvc # YOUR PVC NAME HERE