apiVersion: batch/v1
kind: Job
metadata:
  name: mmpretrain-job-new
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - us-west
                  - us-central
                  - us-east
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                  - unl
                  - ucsd-nrp
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - sdmz-dtn.sox.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - "NVIDIA-A10"
                  - "NVIDIA-GeForce-RTX-3090"
                  - "NVIDIA-GeForce-RTX-3090"
                  - "NVIDIA-TITAN-RTX"
                  - "NVIDIA-RTX-A5000"
                  - "Quadro-RTX-6000"
                  - "Tesla-V100-SXM2-32GB"
                  - "NVIDIA-A40"
                  - "NVIDIA-RTX-A6000"
                  - "Quadro-RTX-8000"
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - weight: 1
        #       preference:
        #         matchExpressions:
        #           # - key: nvidia.com/gpu.product
        #           #   operator: In
        #           #   values:
        #           #     - NVIDIA-A100-SXM4-80GB
        #           #     - NVIDIA-A40
        #           #     - NVIDIA-A100-80GB-PCIe
        #           #     - NVIDIA-RTX-A4000
        #           - key: toplogy.kubernetes.io/region
        #             operator: In
        #             values:
        #               - us-central
        #               - us-east
        #               - us-west
        #               - us-mountain
        #           - key: topology.kubernetes.io/zone
        #             operator: NotIn
        #             values:
        #               - ucsd-nrp
        #               - ucsd
        #               - ucsd-sdsc
        #               - ucsd-sdsc-yu
        #               - sdsu-rci
        #           - key: kubernetes.io/hostname
        #             operator: NotIn
        #             values:
        #               - rci-nrp-gpu-07.sdsu.edu
        #               - rincewind.crbs.ucsd.edu
        #               - node-2-1.sdsc.optiputer.net
      containers:
        - name: mm-convnext
          image: rchristopher27/rc-research-image:mmpretrain2
          workingDir: /rchristopher/data
          env:
              - name: NUM_EPOCHS
                value: "100"
              - name: DATA_NAME
                value: "CIFAR10"
              - name: MILESTONES
                value: "[10, 25, 50]"
              - name: VISUALIZE
                value: "False"
              - name: OPTIMIZER
                value: "SGD"
              - name: LEARNING_RATE
                value: "0.001"
              - name: BATCH_SIZE
                value: "256"
              - name: PYTORCH_CUDA_ALLOC_CONF 
                value: "max_split_size_mb:256"
          command: ["python3", "/rchristopher/data/src/code/mmpretrain_config_runner.py"]
          resources:
            limits:
              memory: 24Gi
              cpu: 12
              nvidia.com/gpu: '1'
            requests:
              memory: 16Gi
              cpu: 8
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: rc-large-pvc
              mountPath: /rchristopher/data
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: rc-large-pvc
          persistentVolumeClaim:
            claimName: rc-large-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
  backoffLimit: 1
