apiVersion: batch/v1
kind: Job
metadata:
  name: rchristopher-cnn-job
spec:
  template:
    spec:
      containers:
        - name: rchristopher-cnn-container
          image: rchristopher27/cnn-image:latest
          workingDir: /data
          command: ["python3", "/data/ucmerced_classification.py"]
          resources:
            limits:
              memory: 10Gi
              cpu: 2
              nvidia.com/gpu: '1'
            requests:
              memory: 10Gi
              cpu: 2
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: rchristopher-pvc
              mountPath: /data
      volumes:
      - name: rchristopher-pvc
        persistentVolumeClaim:
          claimName: rchristopher-pvc
      restartPolicy: Never
  backoffLimit: 1