apiVersion: v1
kind: Pod
metadata:
  name: rchristopher-pod # YOUR POD NAME HERE
spec:
  containers:
    - name: rchristopher-container # YOUR CONTAINER NAME HERE
      image: rchristopher27/cnn-image:latest
      command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
      resources:
        limits:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: '1'
        requests:
          memory: 10Gi
          cpu: 2
          nvidia.com/gpu: '1'
      volumeMounts:
        - mountPath: /data
          name: rchristopher-pvc # YOUR PVC NAME HERE
  volumes:
    - name: rchristopher-pvc # YOUR PVC NAME HERE
      persistentVolumeClaim:
        claimName: rchristopher-pvc-claim # YOUR PVC NAME HERE