apiVersion: v1
kind: Pod
metadata:
  name: rc-pvc-pod # YOUR POD NAME HERE
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central 
  containers:
    - name: rc-pvc-pod # YOUR CONTAINER NAME HERE
      image: ubuntu:20.04
      command: ["sh", "-c", "echo 'Im a new PVC Pod' && sleep infinity"]
      resources:
        limits:
          memory: 10Gi
          cpu: 2
          # nvidia.com/gpu: '1'
        requests:
          memory: 10Gi
          cpu: 2
          # nvidia.com/gpu: '1'
      volumeMounts:
        - mountPath: /data
          name: rchristopher-pvc # YOUR PVC NAME HERE
  volumes:
  - name: rchristopher-pvc # YOUR PVC NAME HERE
    persistentVolumeClaim:
      claimName: rchristopher-pvc # YOUR PVC NAME HERE