apiVersion: v1
kind: Pod
metadata:
  name: rchristopher-pvc-pod # YOUR POD NAME HERE
spec:
  containers:
    - name: rchristopher-pvc-pod # YOUR CONTAINER NAME HERE
      image: ubuntu:20.04
      command: ["sh", "-c", "echo 'I'm a new PVC Pod' && sleep infinity"]
      resources:
        limits:
          memory: 12Gi
          cpu: 2
          nvidia.com/gpu: '1'
        requests:
          memory: 10Gi
          cpu: 2
          nvidia.com/gpu: '1'
      volumeMounts:
        - mountPath: /data
          name: rchristopher-pvc # YOUR PVC NAME HERE
  volumes:
  - name: rchristopher-pvc # YOUR PVC NAME HERE
    persistentVolumeClaim:
      claimName: rchristopher-pvc # YOUR PVC NAME HERE