apiVersion: v1
kind: Pod
metadata:
  name: rchristopher-sklearn-pod
spec:
  containers:
  - name: rchristopher-sklearn-pod
    image: ubuntu:20.04
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
       cpu: 2
       memory: 12Gi
      requests:
        cpu: 2
        memory: 10Gi
    volumeMounts:
    - mountPath: /data
      name: sklearn-pvc
  volumes:
  - name: sklearn-pvc
    persistentVolumeClaim:
     claimName: sklearn-pvc