version: '3'
services:
  rc-research-container:
    image: rchristopher27/rc-research-image:assorted_kfold1
    build:
      context: container
    command: "python3 /rchristopher/data/src/code/Assorted_Kfold_Analysis.py"